name: Build and Deploy Preview
on:
  push:
    branches:
      - dev-preview

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # We skip the default cache because your lockfiles are nested
          
      - name: Build Game Engine (GDJS)
        working-directory: ./GDJS
        run: |
          yarn install
          yarn build

      - name: Build IDE (newIDE)
        working-directory: ./newIDE/app
        run: |
          yarn install
          yarn build
        env:
          PUBLIC_URL: .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: newIDE/app/build
          branch: gh-pages
